/**
 * Hardcoded Fallback Directory Mirrors for Safe Bootstrap.
 *
 * Per Tor spec (dir-spec.txt § 6.2), clients should ship with hardcoded
 * fallback directories to enable safe bootstrap without plain HTTP requests.
 *
 * The fallback data is stored in `fallback-dirs.json` which is:
 * - Generated by `scripts/update-fallback-dirs.ts`
 * - Sourced from Tor Project's official fallback_dirs.inc
 * - Cross-platform compatible (Node.js, browsers, bundlers)
 *
 * To update the fallback list:
 *   npx tsx scripts/update-fallback-dirs.ts
 *
 * Bootstrap process:
 * 1. Connect via TLS to fallback's OR port
 * 2. Verify relay's RSA identity during TLS handshake
 * 3. Use CREATE_FAST for first-hop circuit (no onion key needed)
 * 4. Use RELAY_BEGIN_DIR to fetch directory info over encrypted channel
 *
 * @see https://gitlab.torproject.org/tpo/core/tor/-/blob/main/src/app/config/fallback_dirs.inc
 */

import { LinkSpecifierTypes, AddressTypes, addressAndPortToLinkSpecifier } from './messaging.ts';
import type { PeerInfo } from './circuit.ts';

// Import the JSON data
// Note: For browser compatibility, bundlers handle JSON imports.
// For Node.js, we use import assertion or require as fallback.
import fallbackData from './fallback-dirs.json' with { type: 'json' };

/**
 * Entry from the fallback-dirs.json file.
 */
export type FallbackDirEntry = {
  ip: string;
  orPort: number;
  rsaIdHex: string;
  ipv6?: string;
  ipv6Port?: number;
  nickname?: string;
};

/**
 * Metadata and entries from the JSON file.
 */
export type FallbackDirsData = {
  version: string;
  timestamp: string;
  source: string;
  generatedAt: string;
  entries: FallbackDirEntry[];
};

/**
 * Runtime representation with parsed Buffer for RSA ID.
 */
export type FallbackDirectory = {
  ip: string;
  orPort: number;
  rsaIdDigest: Buffer;
  ipv6?: string;
  ipv6Port?: number;
  nickname?: string;
};

/**
 * The raw JSON data (useful for serialization/inspection).
 */
export const FALLBACK_DIRS_DATA: FallbackDirsData = fallbackData as FallbackDirsData;

/**
 * Parse a JSON entry into a FallbackDirectory with Buffer.
 */
function parseEntry(entry: FallbackDirEntry): FallbackDirectory {
  const rsaIdDigest = Buffer.from(entry.rsaIdHex, 'hex');
  if (rsaIdDigest.length !== 20) {
    throw new Error(`Invalid RSA ID digest length: ${rsaIdDigest.length}, expected 20`);
  }
  const result: FallbackDirectory = {
    ip: entry.ip,
    orPort: entry.orPort,
    rsaIdDigest,
  };
  if (entry.ipv6) result.ipv6 = entry.ipv6;
  if (entry.ipv6Port) result.ipv6Port = entry.ipv6Port;
  if (entry.nickname) result.nickname = entry.nickname;
  return result;
}

/**
 * All fallback directories with parsed Buffers.
 * Parsed once on module load.
 */
export const FALLBACK_DIRECTORIES: FallbackDirectory[] = FALLBACK_DIRS_DATA.entries.map(parseEntry);

/**
 * Alias for FALLBACK_DIRECTORIES.
 * @deprecated Use FALLBACK_DIRECTORIES directly.
 */
export function getFallbackDirectories(): FallbackDirectory[] {
  return FALLBACK_DIRECTORIES;
}

/**
 * Select a random fallback directory.
 */
export function getRandomFallbackDirectory(): FallbackDirectory {
  const dirs = getFallbackDirectories();
  const index = Math.floor(Math.random() * dirs.length);
  const fallback = dirs[index];
  if (!fallback) {
    throw new Error('No fallback directories available');
  }
  return fallback;
}

/**
 * Convert a FallbackDirectory to PeerInfo for circuit building.
 *
 * Note: onionKey is empty because we use CREATE_FAST for fallback connections.
 * CREATE_FAST doesn't require the ntor onion key.
 */
export function fallbackToPeerInfo(fallback: FallbackDirectory): PeerInfo {
  return {
    // Empty onionKey triggers CREATE_FAST instead of CREATE2/ntor
    onionKey: Buffer.alloc(0),
    rsaIdDigest: fallback.rsaIdDigest,
    linkSpecifiers: [
      addressAndPortToLinkSpecifier({
        type: AddressTypes.IPv4,
        ip: fallback.ip,
        port: fallback.orPort,
      }),
      {
        type: LinkSpecifierTypes.LegacyId,
        data: fallback.rsaIdDigest,
      },
    ],
  };
}

/**
 * Legacy helper for manual entry creation.
 * Prefer using the JSON data instead.
 */
export function parseFallbackEntry(
  ip: string,
  orPort: number,
  rsaIdHex: string,
  ipv6?: string,
  ipv6Port?: number
): FallbackDirectory {
  const entry: FallbackDirEntry = { ip, orPort, rsaIdHex };
  if (ipv6 !== undefined) entry.ipv6 = ipv6;
  if (ipv6Port !== undefined) entry.ipv6Port = ipv6Port;
  return parseEntry(entry);
}
